### ISSUE TITLE
biodownloader crashes when directory does not exist yet

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/biodownload#23]
biodownloader should create a new directory if it does not exist yet, but
running this
```
datadir = "data"; 
final IBioDownloader bioDownloader = new BioDownloaderBuilder(Path.of(datadir))
                .hpoJson()
                .hpAnnotation()
                .build();
```
leads to 
```
23:55:28.511 [main] ERROR org.monarchinitiative.biodownload.BioDownloaderBuilder - Path must be a directory.
Directory must be writable.

java.lang.IllegalStateException: Path must be a directory.
Directory must be writable.

	at org.monarchinitiative.biodownload.BioDownloaderBuilder.validate(BioDownloaderBuilder.java:204)
	at org.monarchinitiative.biodownload.BioDownloaderBuilder.build(BioDownloaderBuilder.java:182)
	at org.monarchinitiative.myphenomizer.cmd.DownloadCommand.call(DownloadCommand.java:29)
	at org.monarchinitiative.myphenomizer.cmd.DownloadCommand.call(DownloadCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.monarchinitiative.myphenomizer.Main.main(Main.java:22)

Process finished with exit code 1
```

**Comment by pnrobinson** [comment]
If I create the directory by hand, biodownloader works perfectly.

**Comment by pnrobinson** [comment]
fixed
